<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <VersionPrefix>0.1.0</VersionPrefix>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>YameSoft</Authors>
    <Copyright>Copyright © 2026 YameSoft</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\Images\AddFolder.png" />
    <None Remove="Assets\Images\CancelLanguage.png" />
    <None Remove="Assets\Images\Clear.png" />
    <None Remove="Assets\Images\Delete.png" />
    <None Remove="Assets\Images\Drag.png" />
    <None Remove="Assets\Images\Language.png" />
    <None Remove="Assets\Images\Settings.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Ookii.Dialogs.Wpf" Version="5.0.1" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\RomForge\Common.WPF\Common.WPF.csproj" />
    <ProjectReference Include="..\LibHac\LibHac.csproj" />
    <ProjectReference Include="..\NSW.Core\NSW.Core.csproj" />
    <ProjectReference Include="..\NSW.HacPack\NSW.HacPack.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\icon.ico" />
    <Resource Include="Assets\Images\american.png" />
    <Resource Include="Assets\Images\arabic.png" />
    <Resource Include="Assets\Images\brazilian.png" />
    <Resource Include="Assets\Images\british.png" />
    <Resource Include="Assets\Images\canadian.png" />
    <Resource Include="Assets\Images\CancelLanguage.png" />
    <Resource Include="Assets\Images\chinese.png" />
    <Resource Include="Assets\Images\Clear.png" />
    <Resource Include="Assets\Images\czech.png" />
    <Resource Include="Assets\Images\danish.png" />
    <Resource Include="Assets\Images\Delete.png" />
    <Resource Include="Assets\Images\Drag.png" />
    <Resource Include="Assets\Images\dutch.png" />
    <Resource Include="Assets\Images\finnish.png" />
    <Resource Include="Assets\Images\french.png" />
    <Resource Include="Assets\Images\german.png" />
    <Resource Include="Assets\Images\greek.png" />
    <Resource Include="Assets\Images\hungarian.png" />
    <Resource Include="Assets\Images\indonesian.png" />
    <Resource Include="Assets\Images\italian.png" />
    <Resource Include="Assets\Images\japanese.png" />
    <Resource Include="Assets\Images\korean.png" />
    <Resource Include="Assets\Images\Language.png" />
    <Resource Include="Assets\Images\mexican.png" />
    <Resource Include="Assets\Images\norwegian.png" />
    <Resource Include="Assets\Images\polish.png">
      <CopyToOutputDirectory></CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\portuguese.png" />
    <Resource Include="Assets\Images\romanian.png" />
    <Resource Include="Assets\Images\russian.png" />
    <Resource Include="Assets\Images\slovak.png" />
    <Resource Include="Assets\Images\spanish.png" />
    <Resource Include="Assets\Images\swedish.png" />
    <Resource Include="Assets\Images\taiwanese.png" />
    <Resource Include="Assets\Images\thai.png">
      <CopyToOutputDirectory></CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\ukrainian.png" />
    <Resource Include="Assets\Images\unknown.png" />
    <Resource Include="Assets\Images\vietnamese.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;SYSLIB1045;CS8600;CS8601;CS8603;CS8618;CS8625</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;SYSLIB1045;CS8600;CS8601;CS8603;CS8618;CS8625</NoWarn>
  </PropertyGroup>

</Project>
