<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <VersionPrefix>0.21.1</VersionPrefix>
    <TargetFramework>net8.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>Ryujinx.LibHac</PackageId>
    <Authors>YameSoft</Authors>
    <Copyright>Copyright © 2026 YameSoft</Copyright>
    <PackageProjectUrl>https://git.ryujinx.app/ryubing/libhac</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>

    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>

    <PathMap Condition=" '$(BuildType)' == 'Release' and '$(HasGitDir)' == 'false' ">$(MSBuildProjectDirectory)=C:/LibHac/</PathMap>
    <DeterministicSourcePaths Condition=" '$(BuildType)' == 'Release' and '$(HasGitDir)' == 'true' ">true</DeterministicSourcePaths>

    <NoWarn>$(NoWarn);1591;CS8632;CA1816</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <DefineConstants>$(DefineConstants);ENABLE_ASSERTS</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Compile Condition="Exists('Common\ResultNameResolver.Generated.cs')" Remove="Common\ResultNameResolver.Archive.cs" />
    <Compile Condition="Exists('Common\Keys\DefaultKeySet.Generated.cs')" Remove="Common\Keys\DefaultKeySet.Empty.cs" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>LibHac.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <!-- Packages that are only used when building -->
  <ItemGroup>
    <PackageReference Include="Blake3" Version="2.2.1" />
    <PackageReference Include="ZstdSharp.Port" Version="0.8.8" />
    <PackageReference Include="JetBrains.Annotations" Version="2025.2.4">
      <IncludeAssets>compile; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Common\Common.csproj" />
  </ItemGroup>

</Project>